CREATE DATABASE LTWeb;
USE LTWeb;

DROP TABLE PhoneTbl;

CREATE TABLE PhoneTbl(
	phone_id int PRIMARY KEY IDENTITY(1,1), 
	phone_name NVARCHAR(255), 
	price NVARCHAR(255),
	imgURL NVARCHAR(255),
	brand NVARCHAR(255),
	screen NVARCHAR(255),
	OS NVARCHAR(255),
	CPU NVARCHAR(255),
	RAM NVARCHAR(255),
	camera NVARCHAR(255),
	battery NVARCHAR(255)
);

ALTER TABLE PhoneTbl
ALTER COLUMN phone_name NVARCHAR(255)

select * from PhoneTbl;